AppPedido/AppPedido/Models/AddProductView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AppPedido.Models
{
    public class AddProductView
    {
        [Key]
        public int id { get; set; }

        public int OrderHeaderid { get; set; }

        [Display(Name = "Categoria")]
        public int Categoryid { get; set; }

        [Display(Name = "Producto")]
        public int Productid { get; set; }

        [Display(Name = "Cantidad")]
        public decimal Qty { get; set; }

        [DisplayFormat(DataFormatString = "{0:C2}", ApplyFormatInEditMode = false)]
        [Display(Name = "Precio Unitario")]
        [DataType(DataType.Currency)]
        public decimal UnitPrice { get; set; }
    }

}

AppPedido/AppPedido/Models/OrderHeader.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AppPedido.Models
{
    public class OrderHeader
    {
        [Key]
        [ReadOnly(true)]
        [Display(Name = "OrderNum")]
        public int id { get; set; }
        
        [Required(ErrorMessage = "Campo Cliente es obligatorio")]
        [Display(Name = "Cliente")]
        public int Customerid { get; set; }

        [Display(Name = "Fecha Creacion")]
        public string Date { get; set; }

        [Display(Name = "Total")]
        public decimal Total { get; set; }
        public decimal TotalLine
        {
            get
            {
                if (OrderDetailsls == null)
                {
                    return 0;
                }

                return OrderDetailsls.Sum(od => od.Total);
            }
            set
            {
                
            }
        }


        [Display(Name = "Observation")]
        public string Observation { get; set; }

        [NotMapped]
        public List<OrderDtlTemp> OrderDetailsls { get; set; }

        public virtual Customer Customer { get; set; }

        public ICollection<OrderDetail> OrderDetails { get; set; }

    }
}

AppPedido/AppPedido/Controllers/OrderHeadersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppPedido.Models;

namespace AppPedido.Controllers
{
    public class OrderHeadersController : Controller
    {
        private Context db = new Context();

        public ActionResult AddProduct()
        {
            var categories = db.Categories.ToList();
            categories.Add(new Category
            {
                id = 0,
                CategoryName = "[Seleccione Categoria]"
            });
            ViewBag.Categoryid = new SelectList(categories.OrderBy(c=>c.id), "id", "CategoryName");

            var products = db.Products.ToList();
            products.Add(new Product
            {
                id = 0,
                ProductTitle = "[Seleccione Producto]"
            });
            ViewBag.Productid = new SelectList(products.OrderBy(c => c.id), "id", "ProductTitle");
            return View();
        }

        [HttpPost]
        public ActionResult AddProduct(AddProductView view)
        {
            int line=db.OrderDtlTemps.Count();
            var product = db.Products.Find(view.Productid);
            var OrderDtlTemp = new OrderDtlTemp
            {
                OrderDetailLine = line + 1,
                Productid = view.Productid,
                ProductNUm = product.ProductNum,
                ProductTitle = product.ProductTitle,
                UnitPrice = product.UnitPrice,
                Qty = view.Qty,
                Total = product.UnitPrice * view.Qty
            };
            db.OrderDtlTemps.Add(OrderDtlTemp);
            db.SaveChanges();
            return RedirectToAction("Create");
        }


        // GET: OrderHeaders
        public ActionResult Index()
        {
            var orderHeaders = db.OrderHeaders.Include(o => o.Customer);
            return View(orderHeaders.ToList());
        }

        // GET: OrderHeaders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderHeader orderHeader = db.OrderHeaders.Find(id);
            orderHeader.OrderDetails = db.OrderDetails.Where(o => o.OrderHeaderid == id).ToList();
            if (orderHeader == null)
            {
                return HttpNotFound();
            }
            return View(orderHeader);
        }

        // GET: OrderHeaders/Create
        public ActionResult Create()
        {
            ViewBag.Customerid = new SelectList(db.Customers, "id", "Name");
            var OrderHeader = new OrderHeader
            {
                OrderDetailsls=db.OrderDtlTemps.ToList()
            };
            return View(OrderHeader);
        }

        // POST: OrderHeaders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrderHeader orderHeader)
        {
            if (ModelState.IsValid)
            {
                var orderDtlTemps = db.OrderDtlTemps.ToList();
                orderHeader.Date = DateTime.Now.ToString();
                orderHeader.Total= orderDtlTemps.Sum(od => od.Total);
                db.OrderHeaders.Add(orderHeader);
                db.SaveChanges();
                
                foreach (var item in orderDtlTemps)
                {
                    var orderDetail = new OrderDetail
                    {
                        OrderDetailLine = item.OrderDetailLine,
                        OrderHeaderid = orderHeader.id,
                        Productid=item.Productid,
                        Qty=item.Qty,
                        Total=item.Total
                    };
                    db.OrderDetails.Add(orderDetail);
                    db.OrderDtlTemps.Remove(item);
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Customerid = new SelectList(db.Customers, "id", "Name", orderHeader.Customerid);
            return View(orderHeader);
        }

        // GET: OrderHeaders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderHeader orderHeader = db.OrderHeaders.Find(id);
            if (orderHeader == null)
            {
                return HttpNotFound();
            }
            ViewBag.Customerid = new SelectList(db.Customers, "id", "Name", orderHeader.Customerid);
            return View(orderHeader);
        }

        // POST: OrderHeaders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Customerid,Date,Total,Observation")] OrderHeader orderHeader)
        {
            if (ModelState.IsValid)
            {
                db.Entry(orderHeader).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Customerid = new SelectList(db.Customers, "id", "Name", orderHeader.Customerid);
            return View(orderHeader);
        }

        // GET: OrderHeaders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderHeader orderHeader = db.OrderHeaders.Find(id);
            orderHeader.OrderDetails = db.OrderDetails.Where(o => o.OrderHeaderid == id).ToList();
            if (orderHeader == null)
            {
                return HttpNotFound();
            }
            return View(orderHeader);
        }

        // POST: OrderHeaders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OrderHeader orderHeader = db.OrderHeaders.Find(id);
            foreach (var item in db.OrderDetails.Where(o => o.OrderHeaderid == id).ToList())
            {
                db.OrderDetails.Remove(item);
            }
            db.OrderHeaders.Remove(orderHeader);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        #region JsonResult
        public JsonResult GetProducts(int Categoryid)
        {
            if(Categoryid==0)
            {
                var products2 = db.Products.ToList();
                products2.Add(new Product
                {
                    id = 0,
                    ProductTitle = "[Seleccione Producto]"
                });

                return Json(new SelectList(products2.OrderBy(c => c.id), "id", "ProductTitle"));

            }

            db.Configuration.ProxyCreationEnabled = false;
            var productcategory = db.ProductCategories.Where(p => p.id == Categoryid);

            var products = (from item in db.Products
                           join item2 in productcategory on item.id equals item2.Productid
                           select item).ToList();
            products.Add(new Product
            {
                id = 0,
                ProductTitle = "[Seleccione Producto]"
            });
            return Json(new SelectList(products.OrderBy(c => c.id), "id", "ProductTitle"));
        }
        public JsonResult GetUnitPrice(int? Productid)
        {
            if (Productid==null || Productid == 0)
            {             
                var product = new Product
                {
                    id=0,
                    ProductNum="",
                    ProductTitle="",
                    UnitPrice=0
                };
                return Json(product.UnitPrice, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var product = db.Products.Where(p => p.id == Productid).FirstOrDefault();
                return Json(product.UnitPrice, JsonRequestBehavior.AllowGet);

            }
        }
        
        #endregion
    }
}

AppPedido/AppPedido/Views/OrderHeaders/AddProduct.cshtml
@model AppPedido.Models.AddProductView

@{
    ViewBag.Title = "AddProduct";
}

<h2>AddProduct</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>AddProductView</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Categoryid, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Categoryid", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Categoryid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Productid, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Productid", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Productid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Qty, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Qty, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Qty, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control", @readonly= "readonly" } })
            @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $("#add").click(function () {
            if ($(this).valid()) {
                $("#add").prop("disabled", true);
                $("#frm").submit();
        }
    })
    $(document).ready
        (
        function () {
            $("#Categoryid").change(function () {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetProducts")',
                    dataType: 'json',
                    data: { Categoryid: $("#Categoryid").val() },
                    success: function (products) {
                        $("#Productid").empty();
                        $.each(products, function (i, product) {
                            $("#Productid").append('<option value="' + product.Value + '">' + product.Text + '</option>');
                        });
                        //$("#Productid").attr("value", 0);
                    },
                });
            })
        }
        )
      $(document).ready(function () {
            $("#Productid").change(function () {
                $("#UnitPrice").empty;
        $.ajax({
            type: 'POST',
            url: '@Url.Action("GetUnitPrice")',
            dataType: 'json',
            data: { Productid: $("#Productid").val()},
            success: function (unitpice) {
                $("#UnitPrice").prop("value", unitpice);
            },
        });
        return false;
    })
    })
    </script>


}

AppPedido/AppPedido/Views/OrderHeaders/Create.cshtml
@model AppPedido.Models.OrderHeader

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>OrderHeader</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control",@readonly = "readonly"} })
            @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Customerid, "Customerid", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Customerid", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Customerid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TotalLine, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TotalLine, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.TotalLine, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Observation, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Observation, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Observation, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear orden" class="btn btn-default" />
        </div>
        <div>@Html.ActionLink("+ Agregar Producto", "AddProduct", "OrderHeaders", null, new { @id = "SubmitAddProduct", @class = "btn btn-warning" })</div>
    </div>
</div>
}
@if (Model != null)
{
    <table class="table">
        <tr>
            <th>
                Linea
            </th>
            <th>
                Numero Producto
            </th>
            <th>
                Titulo Producto
            </th>
            <th>
                Cantidad
            </th>
            <th>
                Precio unitario
            </th>
            <th>
                Total
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model.OrderDetailsls)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDetailLine)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductNUm)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Qty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnitPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
        </tr>
        }
        </table>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppPedido/AppPedido/Views/OrderHeaders/Delete.cshtml
@model AppPedido.Models.OrderHeader

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrderHeader</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.DocumentNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.DocumentNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observation)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
@if (Model != null)
{
    <table class="table">
        <tr>
            <th>
                Linea
            </th>
            <th>
                Numero Producto
            </th>
            <th>
                Titulo Producto
            </th>
            <th>
                Cantidad
            </th>
            <th>
                Precio unitario
            </th>
            <th>
                Total
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model.OrderDetails)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderDetailLine)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.ProductNum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.ProductTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Qty)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.UnitPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
            </tr>
        }
    </table>
}

AppPedido/AppPedido/Views/OrderHeaders/Details.cshtml
@model AppPedido.Models.OrderHeader

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>OrderHeader</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.DocumentNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.DocumentNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observation)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
@if (Model != null)
{
    <table class="table">
        <tr>
            <th>
                Linea
            </th>
            <th>
                Numero Producto
            </th>
            <th>
                Titulo Producto
            </th>
            <th>
                Cantidad
            </th>
            <th>
                Precio unitario
            </th>
            <th>
                Total
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model.OrderDetails)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderDetailLine)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.ProductNum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.ProductTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Qty)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.UnitPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
            </tr>
        }
    </table>
}

AppPedido/AppPedido/Views/OrderHeaders/Edit.cshtml
@model AppPedido.Models.OrderHeader

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OrderHeader</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Customerid, "Customerid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Customerid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Customerid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppPedido/AppPedido/Views/OrderHeaders/Index.cshtml
@model IEnumerable<AppPedido.Models.OrderHeader>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Customer.DocumentNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Observation)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.DocumentNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Observation)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>